sudo: false

language: php

addons:
  apt:
    sources:
      - couchbase-precise
    packages:
      - libcouchbase-dev
      - libcouchbase2-libevent

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: 7
    - php: hhvm

notifications:
  email: "siad.ardroumli@gmail.com"

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - pecl install couchbase

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
  - ./bin/phpunit